teleop_twist_joy_node:
  ros__parameters:
    mac_address: "5C:BA:37:25:55:A7"

    require_enable_button: False

    axis_linear: # Left trigger
      x: 2
    scale_linear: # Max linear speed [m/s]
      x: 0.6

    axis_angular: # Left thumb stick horizontal
      yaw: 0
    scale_angular: # Max angular speed: scale * [-1, 1] should be in [rad/s]
      yaw: 2.5

    # if a pad has two triggers, first one can be linear forward, and the second one to be linear backward
    read_linear_from_triggers: True
    axis_linear_backward: # Right trigger
      x: 5

    # turbo settings
    enable_turbo_button: 3 # Y button
    scale_linear_turbo:
      x: 1.4
    scale_angular_turbo:
      yaw: 3.5
